name: Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "docs/docs/**"
    branches:
      - main

jobs:
  build:
    name: Build Monorepo
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@main

      - name: Install pnpm
        uses: pnpm/action-setup@master

      - name: Install Node
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Run Tests
        run: bun run test

      - name: Run Lint
        run: bun run lint
